---
- hosts: all
  become: yes
  #remote_user: root
  gather_facts: no
  pre_tasks:
    - name: install git
      apt:
        name: git
        state: present
        
    - name: checkout CIS v 1.1.0 hardening repository
      ansible.builtin.git:
        repo: 'https://github.com/elfrin-ui/cis-ansible-ubuntu-20.04'
        dest: /etc/ansible/roles/cis-ansible-ubuntu-20.04
        version: master
  roles:
    - cis-ansible-ubuntu-20.04